[build]
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

# Redirects (igual ao seu server.js original)
[[redirects]]
  from = "/api/agendamentos/:cliente"
  to = "/.netlify/functions/agendamentos/:cliente"
  status = 200

[[redirects]]
  from = "/api/agendar/:cliente"
  to = "/.netlify/functions/agendamentos/:cliente"
  status = 200

[[redirects]]
  from = "/api/agendamentos/:cliente/confirmar/:id"
  to = "/.netlify/functions/agendamentos/:cliente/confirmar/:id"
  status = 200

[[redirects]]
  from = "/api/agendamentos/:cliente/cancelar/:id"
  to = "/.netlify/functions/agendamentos/:cliente/cancelar/:id"
  status = 200

[[redirects]]
  from = "/api/agendamentos/:cliente/reagendar/:id"
  to = "/.netlify/functions/agendamentos/:cliente/reagendar/:id"
  status = 200

# Serve o frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
